# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uic/game-menu.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TPRGameMenu(object):
    def setupUi(self, TPRGameMenu):
        TPRGameMenu.setObjectName("TPRGameMenu")
        TPRGameMenu.resize(1168, 760)
        self.GameMenuWidget = QtWidgets.QWidget(TPRGameMenu)
        self.GameMenuWidget.setObjectName("GameMenuWidget")
        self.line = QtWidgets.QFrame(self.GameMenuWidget)
        self.line.setGeometry(QtCore.QRect(10, 80, 1171, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.GameMenuWidget)
        self.line_2.setGeometry(QtCore.QRect(380, 0, 20, 770))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.btn_clear_log = QtWidgets.QPushButton(self.GameMenuWidget)
        self.btn_clear_log.setGeometry(QtCore.QRect(240, 690, 130, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_clear_log.setFont(font)
        self.btn_clear_log.setObjectName("btn_clear_log")
        self.btn_send_message = QtWidgets.QPushButton(self.GameMenuWidget)
        self.btn_send_message.setGeometry(QtCore.QRect(20, 690, 200, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_send_message.setFont(font)
        self.btn_send_message.setObjectName("btn_send_message")
        self.lbl_title = QtWidgets.QLabel(self.GameMenuWidget)
        self.lbl_title.setGeometry(QtCore.QRect(20, 20, 350, 50))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lbl_title.setFont(font)
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setObjectName("lbl_title")
        self.txt_messagebox = QtWidgets.QLineEdit(self.GameMenuWidget)
        self.txt_messagebox.setGeometry(QtCore.QRect(20, 640, 350, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_messagebox.setFont(font)
        self.txt_messagebox.setText("")
        self.txt_messagebox.setObjectName("txt_messagebox")
        self.list_log_entries = QtWidgets.QListWidget(self.GameMenuWidget)
        self.list_log_entries.setGeometry(QtCore.QRect(20, 110, 350, 490))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.list_log_entries.setFont(font)
        self.list_log_entries.setAlternatingRowColors(True)
        self.list_log_entries.setWordWrap(True)
        self.list_log_entries.setObjectName("list_log_entries")
        self.group_player1 = QtWidgets.QGroupBox(self.GameMenuWidget)
        self.group_player1.setGeometry(QtCore.QRect(410, 110, 220, 170))
        self.group_player1.setObjectName("group_player1")
        self.lbl_p1_name_lbl = QtWidgets.QLabel(self.group_player1)
        self.lbl_p1_name_lbl.setGeometry(QtCore.QRect(10, 20, 80, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p1_name_lbl.setFont(font)
        self.lbl_p1_name_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p1_name_lbl.setObjectName("lbl_p1_name_lbl")
        self.lbl_p1_name = QtWidgets.QLabel(self.group_player1)
        self.lbl_p1_name.setGeometry(QtCore.QRect(100, 20, 120, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lbl_p1_name.setFont(font)
        self.lbl_p1_name.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p1_name.setObjectName("lbl_p1_name")
        self.lbl_p1_profession = QtWidgets.QLabel(self.group_player1)
        self.lbl_p1_profession.setGeometry(QtCore.QRect(100, 40, 120, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lbl_p1_profession.setFont(font)
        self.lbl_p1_profession.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p1_profession.setObjectName("lbl_p1_profession")
        self.lbl_p1_profession_lbl = QtWidgets.QLabel(self.group_player1)
        self.lbl_p1_profession_lbl.setGeometry(QtCore.QRect(10, 40, 80, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p1_profession_lbl.setFont(font)
        self.lbl_p1_profession_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p1_profession_lbl.setObjectName("lbl_p1_profession_lbl")
        self.lbl_p1_stats_lbl = QtWidgets.QLabel(self.group_player1)
        self.lbl_p1_stats_lbl.setGeometry(QtCore.QRect(10, 100, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p1_stats_lbl.setFont(font)
        self.lbl_p1_stats_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p1_stats_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_p1_stats_lbl.setObjectName("lbl_p1_stats_lbl")
        self.line_3 = QtWidgets.QFrame(self.group_player1)
        self.line_3.setGeometry(QtCore.QRect(50, 70, 20, 100))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.group_player1)
        self.line_4.setGeometry(QtCore.QRect(0, 60, 220, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.lbl_p1_hp_lbl = QtWidgets.QLabel(self.group_player1)
        self.lbl_p1_hp_lbl.setGeometry(QtCore.QRect(70, 80, 47, 20))
        self.lbl_p1_hp_lbl.setObjectName("lbl_p1_hp_lbl")
        self.lbl_p1_ap_lbl = QtWidgets.QLabel(self.group_player1)
        self.lbl_p1_ap_lbl.setGeometry(QtCore.QRect(70, 100, 47, 20))
        self.lbl_p1_ap_lbl.setObjectName("lbl_p1_ap_lbl")
        self.lbl_p1_mana_lbl = QtWidgets.QLabel(self.group_player1)
        self.lbl_p1_mana_lbl.setGeometry(QtCore.QRect(70, 120, 47, 20))
        self.lbl_p1_mana_lbl.setObjectName("lbl_p1_mana_lbl")
        self.lbl_p1_turn_in_lbl = QtWidgets.QLabel(self.group_player1)
        self.lbl_p1_turn_in_lbl.setGeometry(QtCore.QRect(70, 140, 47, 20))
        self.lbl_p1_turn_in_lbl.setObjectName("lbl_p1_turn_in_lbl")
        self.lbl_p1_ap = QtWidgets.QLabel(self.group_player1)
        self.lbl_p1_ap.setGeometry(QtCore.QRect(110, 100, 40, 20))
        self.lbl_p1_ap.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_p1_ap.setObjectName("lbl_p1_ap")
        self.lbl_p1_mana = QtWidgets.QLabel(self.group_player1)
        self.lbl_p1_mana.setGeometry(QtCore.QRect(110, 120, 40, 20))
        self.lbl_p1_mana.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_p1_mana.setObjectName("lbl_p1_mana")
        self.lbl_p1_hp = QtWidgets.QLabel(self.group_player1)
        self.lbl_p1_hp.setGeometry(QtCore.QRect(110, 80, 40, 20))
        self.lbl_p1_hp.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_p1_hp.setObjectName("lbl_p1_hp")
        self.lbl_p1_turn_in = QtWidgets.QLabel(self.group_player1)
        self.lbl_p1_turn_in.setGeometry(QtCore.QRect(110, 140, 40, 20))
        self.lbl_p1_turn_in.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_p1_turn_in.setObjectName("lbl_p1_turn_in")
        self.btn_p1_select = QtWidgets.QPushButton(self.group_player1)
        self.btn_p1_select.setGeometry(QtCore.QRect(170, 80, 40, 40))
        self.btn_p1_select.setObjectName("btn_p1_select")
        self.line_5 = QtWidgets.QFrame(self.group_player1)
        self.line_5.setGeometry(QtCore.QRect(150, 70, 20, 100))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.btn_p1_info = QtWidgets.QPushButton(self.group_player1)
        self.btn_p1_info.setGeometry(QtCore.QRect(170, 120, 40, 40))
        self.btn_p1_info.setObjectName("btn_p1_info")
        self.group_player2 = QtWidgets.QGroupBox(self.GameMenuWidget)
        self.group_player2.setGeometry(QtCore.QRect(670, 110, 220, 170))
        self.group_player2.setObjectName("group_player2")
        self.lbl_p2_name_lbl = QtWidgets.QLabel(self.group_player2)
        self.lbl_p2_name_lbl.setGeometry(QtCore.QRect(10, 20, 80, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p2_name_lbl.setFont(font)
        self.lbl_p2_name_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p2_name_lbl.setObjectName("lbl_p2_name_lbl")
        self.lbl_p2_name = QtWidgets.QLabel(self.group_player2)
        self.lbl_p2_name.setGeometry(QtCore.QRect(100, 20, 120, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lbl_p2_name.setFont(font)
        self.lbl_p2_name.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p2_name.setObjectName("lbl_p2_name")
        self.lbl_p2_profession = QtWidgets.QLabel(self.group_player2)
        self.lbl_p2_profession.setGeometry(QtCore.QRect(100, 40, 120, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lbl_p2_profession.setFont(font)
        self.lbl_p2_profession.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p2_profession.setObjectName("lbl_p2_profession")
        self.lbl_p2_profession_lbl = QtWidgets.QLabel(self.group_player2)
        self.lbl_p2_profession_lbl.setGeometry(QtCore.QRect(10, 40, 80, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p2_profession_lbl.setFont(font)
        self.lbl_p2_profession_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p2_profession_lbl.setObjectName("lbl_p2_profession_lbl")
        self.lbl_p2_stats_lbl = QtWidgets.QLabel(self.group_player2)
        self.lbl_p2_stats_lbl.setGeometry(QtCore.QRect(10, 100, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p2_stats_lbl.setFont(font)
        self.lbl_p2_stats_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p2_stats_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_p2_stats_lbl.setObjectName("lbl_p2_stats_lbl")
        self.line_7 = QtWidgets.QFrame(self.group_player2)
        self.line_7.setGeometry(QtCore.QRect(50, 70, 20, 100))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.group_player2)
        self.line_8.setGeometry(QtCore.QRect(0, 60, 220, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.lbl_p2_hp_lbl = QtWidgets.QLabel(self.group_player2)
        self.lbl_p2_hp_lbl.setGeometry(QtCore.QRect(70, 80, 47, 20))
        self.lbl_p2_hp_lbl.setObjectName("lbl_p2_hp_lbl")
        self.lbl_p2_ap_lbl = QtWidgets.QLabel(self.group_player2)
        self.lbl_p2_ap_lbl.setGeometry(QtCore.QRect(70, 100, 47, 20))
        self.lbl_p2_ap_lbl.setObjectName("lbl_p2_ap_lbl")
        self.lbl_p2_mana_lbl = QtWidgets.QLabel(self.group_player2)
        self.lbl_p2_mana_lbl.setGeometry(QtCore.QRect(70, 120, 47, 20))
        self.lbl_p2_mana_lbl.setObjectName("lbl_p2_mana_lbl")
        self.lbl_p2_turn_in_lbl = QtWidgets.QLabel(self.group_player2)
        self.lbl_p2_turn_in_lbl.setGeometry(QtCore.QRect(70, 140, 47, 20))
        self.lbl_p2_turn_in_lbl.setObjectName("lbl_p2_turn_in_lbl")
        self.lbl_p2_ap = QtWidgets.QLabel(self.group_player2)
        self.lbl_p2_ap.setGeometry(QtCore.QRect(110, 100, 40, 20))
        self.lbl_p2_ap.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_p2_ap.setObjectName("lbl_p2_ap")
        self.lbl_p2_mana = QtWidgets.QLabel(self.group_player2)
        self.lbl_p2_mana.setGeometry(QtCore.QRect(110, 120, 40, 20))
        self.lbl_p2_mana.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_p2_mana.setObjectName("lbl_p2_mana")
        self.lbl_p2_hp = QtWidgets.QLabel(self.group_player2)
        self.lbl_p2_hp.setGeometry(QtCore.QRect(110, 80, 40, 20))
        self.lbl_p2_hp.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_p2_hp.setObjectName("lbl_p2_hp")
        self.lbl_p2_turn_in = QtWidgets.QLabel(self.group_player2)
        self.lbl_p2_turn_in.setGeometry(QtCore.QRect(110, 140, 40, 20))
        self.lbl_p2_turn_in.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_p2_turn_in.setObjectName("lbl_p2_turn_in")
        self.btn_p2_select = QtWidgets.QPushButton(self.group_player2)
        self.btn_p2_select.setGeometry(QtCore.QRect(170, 80, 40, 40))
        self.btn_p2_select.setObjectName("btn_p2_select")
        self.line_9 = QtWidgets.QFrame(self.group_player2)
        self.line_9.setGeometry(QtCore.QRect(150, 70, 20, 100))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.btn_p2_info = QtWidgets.QPushButton(self.group_player2)
        self.btn_p2_info.setGeometry(QtCore.QRect(170, 120, 40, 40))
        self.btn_p2_info.setObjectName("btn_p2_info")
        self.group_player3 = QtWidgets.QGroupBox(self.GameMenuWidget)
        self.group_player3.setGeometry(QtCore.QRect(930, 110, 220, 170))
        self.group_player3.setObjectName("group_player3")
        self.lbl_p3_name_lbl = QtWidgets.QLabel(self.group_player3)
        self.lbl_p3_name_lbl.setGeometry(QtCore.QRect(10, 20, 80, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p3_name_lbl.setFont(font)
        self.lbl_p3_name_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p3_name_lbl.setObjectName("lbl_p3_name_lbl")
        self.lbl_p3_name = QtWidgets.QLabel(self.group_player3)
        self.lbl_p3_name.setGeometry(QtCore.QRect(100, 20, 120, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lbl_p3_name.setFont(font)
        self.lbl_p3_name.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p3_name.setObjectName("lbl_p3_name")
        self.lbl_p3_profession = QtWidgets.QLabel(self.group_player3)
        self.lbl_p3_profession.setGeometry(QtCore.QRect(100, 40, 120, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lbl_p3_profession.setFont(font)
        self.lbl_p3_profession.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p3_profession.setObjectName("lbl_p3_profession")
        self.lbl_p3_profession_lbl = QtWidgets.QLabel(self.group_player3)
        self.lbl_p3_profession_lbl.setGeometry(QtCore.QRect(10, 40, 80, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p3_profession_lbl.setFont(font)
        self.lbl_p3_profession_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p3_profession_lbl.setObjectName("lbl_p3_profession_lbl")
        self.lbl_p3_stats_lbl = QtWidgets.QLabel(self.group_player3)
        self.lbl_p3_stats_lbl.setGeometry(QtCore.QRect(10, 100, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p3_stats_lbl.setFont(font)
        self.lbl_p3_stats_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p3_stats_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_p3_stats_lbl.setObjectName("lbl_p3_stats_lbl")
        self.line_11 = QtWidgets.QFrame(self.group_player3)
        self.line_11.setGeometry(QtCore.QRect(50, 70, 20, 100))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_20 = QtWidgets.QFrame(self.group_player3)
        self.line_20.setGeometry(QtCore.QRect(0, 60, 220, 20))
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.lbl_p3_hp_lbl = QtWidgets.QLabel(self.group_player3)
        self.lbl_p3_hp_lbl.setGeometry(QtCore.QRect(70, 80, 47, 20))
        self.lbl_p3_hp_lbl.setObjectName("lbl_p3_hp_lbl")
        self.lbl_p3_ap_lbl = QtWidgets.QLabel(self.group_player3)
        self.lbl_p3_ap_lbl.setGeometry(QtCore.QRect(70, 100, 47, 20))
        self.lbl_p3_ap_lbl.setObjectName("lbl_p3_ap_lbl")
        self.lbl_p3_mana_lbl = QtWidgets.QLabel(self.group_player3)
        self.lbl_p3_mana_lbl.setGeometry(QtCore.QRect(70, 120, 47, 20))
        self.lbl_p3_mana_lbl.setObjectName("lbl_p3_mana_lbl")
        self.lbl_p3_turn_in_lbl = QtWidgets.QLabel(self.group_player3)
        self.lbl_p3_turn_in_lbl.setGeometry(QtCore.QRect(70, 140, 47, 20))
        self.lbl_p3_turn_in_lbl.setObjectName("lbl_p3_turn_in_lbl")
        self.lbl_p3_ap = QtWidgets.QLabel(self.group_player3)
        self.lbl_p3_ap.setGeometry(QtCore.QRect(110, 100, 40, 20))
        self.lbl_p3_ap.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_p3_ap.setObjectName("lbl_p3_ap")
        self.lbl_p3_mana = QtWidgets.QLabel(self.group_player3)
        self.lbl_p3_mana.setGeometry(QtCore.QRect(110, 120, 40, 20))
        self.lbl_p3_mana.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_p3_mana.setObjectName("lbl_p3_mana")
        self.lbl_p3_hp = QtWidgets.QLabel(self.group_player3)
        self.lbl_p3_hp.setGeometry(QtCore.QRect(110, 80, 40, 20))
        self.lbl_p3_hp.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_p3_hp.setObjectName("lbl_p3_hp")
        self.lbl_p3_turn_in = QtWidgets.QLabel(self.group_player3)
        self.lbl_p3_turn_in.setGeometry(QtCore.QRect(110, 140, 40, 20))
        self.lbl_p3_turn_in.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_p3_turn_in.setObjectName("lbl_p3_turn_in")
        self.btn_p3_select = QtWidgets.QPushButton(self.group_player3)
        self.btn_p3_select.setGeometry(QtCore.QRect(170, 80, 40, 40))
        self.btn_p3_select.setObjectName("btn_p3_select")
        self.line_10 = QtWidgets.QFrame(self.group_player3)
        self.line_10.setGeometry(QtCore.QRect(150, 70, 20, 100))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.btn_p3_info = QtWidgets.QPushButton(self.group_player3)
        self.btn_p3_info.setGeometry(QtCore.QRect(170, 120, 40, 40))
        self.btn_p3_info.setObjectName("btn_p3_info")
        self.group_player5 = QtWidgets.QGroupBox(self.GameMenuWidget)
        self.group_player5.setGeometry(QtCore.QRect(670, 310, 220, 170))
        self.group_player5.setObjectName("group_player5")
        self.lbl_p5_name_lbl = QtWidgets.QLabel(self.group_player5)
        self.lbl_p5_name_lbl.setGeometry(QtCore.QRect(10, 20, 80, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p5_name_lbl.setFont(font)
        self.lbl_p5_name_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p5_name_lbl.setObjectName("lbl_p5_name_lbl")
        self.lbl_p5_name = QtWidgets.QLabel(self.group_player5)
        self.lbl_p5_name.setGeometry(QtCore.QRect(100, 20, 120, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lbl_p5_name.setFont(font)
        self.lbl_p5_name.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p5_name.setObjectName("lbl_p5_name")
        self.lbl_p5_profession = QtWidgets.QLabel(self.group_player5)
        self.lbl_p5_profession.setGeometry(QtCore.QRect(100, 40, 120, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lbl_p5_profession.setFont(font)
        self.lbl_p5_profession.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p5_profession.setObjectName("lbl_p5_profession")
        self.lbl_p5_profession_lbl = QtWidgets.QLabel(self.group_player5)
        self.lbl_p5_profession_lbl.setGeometry(QtCore.QRect(10, 40, 80, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p5_profession_lbl.setFont(font)
        self.lbl_p5_profession_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p5_profession_lbl.setObjectName("lbl_p5_profession_lbl")
        self.lbl_p5_stats_lbl = QtWidgets.QLabel(self.group_player5)
        self.lbl_p5_stats_lbl.setGeometry(QtCore.QRect(10, 100, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p5_stats_lbl.setFont(font)
        self.lbl_p5_stats_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p5_stats_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_p5_stats_lbl.setObjectName("lbl_p5_stats_lbl")
        self.line_21 = QtWidgets.QFrame(self.group_player5)
        self.line_21.setGeometry(QtCore.QRect(50, 70, 20, 100))
        self.line_21.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.line_22 = QtWidgets.QFrame(self.group_player5)
        self.line_22.setGeometry(QtCore.QRect(0, 60, 220, 20))
        self.line_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.lbl_p5_hp_lbl = QtWidgets.QLabel(self.group_player5)
        self.lbl_p5_hp_lbl.setGeometry(QtCore.QRect(70, 80, 47, 20))
        self.lbl_p5_hp_lbl.setObjectName("lbl_p5_hp_lbl")
        self.lbl_p5_ap_lbl = QtWidgets.QLabel(self.group_player5)
        self.lbl_p5_ap_lbl.setGeometry(QtCore.QRect(70, 100, 47, 20))
        self.lbl_p5_ap_lbl.setObjectName("lbl_p5_ap_lbl")
        self.lbl_p5_mana_lbl = QtWidgets.QLabel(self.group_player5)
        self.lbl_p5_mana_lbl.setGeometry(QtCore.QRect(70, 120, 47, 20))
        self.lbl_p5_mana_lbl.setObjectName("lbl_p5_mana_lbl")
        self.lbl_p5_turn_in_lbl = QtWidgets.QLabel(self.group_player5)
        self.lbl_p5_turn_in_lbl.setGeometry(QtCore.QRect(70, 140, 47, 20))
        self.lbl_p5_turn_in_lbl.setObjectName("lbl_p5_turn_in_lbl")
        self.lbl_p5_ap = QtWidgets.QLabel(self.group_player5)
        self.lbl_p5_ap.setGeometry(QtCore.QRect(110, 100, 40, 20))
        self.lbl_p5_ap.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_p5_ap.setObjectName("lbl_p5_ap")
        self.lbl_p5_mana = QtWidgets.QLabel(self.group_player5)
        self.lbl_p5_mana.setGeometry(QtCore.QRect(110, 120, 40, 20))
        self.lbl_p5_mana.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_p5_mana.setObjectName("lbl_p5_mana")
        self.lbl_p5_hp = QtWidgets.QLabel(self.group_player5)
        self.lbl_p5_hp.setGeometry(QtCore.QRect(110, 80, 40, 20))
        self.lbl_p5_hp.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_p5_hp.setObjectName("lbl_p5_hp")
        self.lbl_p5_turn_in = QtWidgets.QLabel(self.group_player5)
        self.lbl_p5_turn_in.setGeometry(QtCore.QRect(110, 140, 40, 20))
        self.lbl_p5_turn_in.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_p5_turn_in.setObjectName("lbl_p5_turn_in")
        self.btn_p5_select = QtWidgets.QPushButton(self.group_player5)
        self.btn_p5_select.setGeometry(QtCore.QRect(170, 80, 40, 40))
        self.btn_p5_select.setObjectName("btn_p5_select")
        self.line_12 = QtWidgets.QFrame(self.group_player5)
        self.line_12.setGeometry(QtCore.QRect(150, 70, 20, 100))
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.btn_p5_info = QtWidgets.QPushButton(self.group_player5)
        self.btn_p5_info.setGeometry(QtCore.QRect(170, 120, 40, 40))
        self.btn_p5_info.setObjectName("btn_p5_info")
        self.group_player6 = QtWidgets.QGroupBox(self.GameMenuWidget)
        self.group_player6.setGeometry(QtCore.QRect(930, 310, 220, 170))
        self.group_player6.setObjectName("group_player6")
        self.lbl_p6_name_lbl = QtWidgets.QLabel(self.group_player6)
        self.lbl_p6_name_lbl.setGeometry(QtCore.QRect(10, 20, 80, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p6_name_lbl.setFont(font)
        self.lbl_p6_name_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p6_name_lbl.setObjectName("lbl_p6_name_lbl")
        self.lbl_p6_name = QtWidgets.QLabel(self.group_player6)
        self.lbl_p6_name.setGeometry(QtCore.QRect(100, 20, 120, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lbl_p6_name.setFont(font)
        self.lbl_p6_name.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p6_name.setObjectName("lbl_p6_name")
        self.lbl_p6_profession = QtWidgets.QLabel(self.group_player6)
        self.lbl_p6_profession.setGeometry(QtCore.QRect(100, 40, 120, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lbl_p6_profession.setFont(font)
        self.lbl_p6_profession.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p6_profession.setObjectName("lbl_p6_profession")
        self.lbl_p6_profession_lbl = QtWidgets.QLabel(self.group_player6)
        self.lbl_p6_profession_lbl.setGeometry(QtCore.QRect(10, 40, 80, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p6_profession_lbl.setFont(font)
        self.lbl_p6_profession_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p6_profession_lbl.setObjectName("lbl_p6_profession_lbl")
        self.lbl_p6_stats_lbl = QtWidgets.QLabel(self.group_player6)
        self.lbl_p6_stats_lbl.setGeometry(QtCore.QRect(10, 100, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p6_stats_lbl.setFont(font)
        self.lbl_p6_stats_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p6_stats_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_p6_stats_lbl.setObjectName("lbl_p6_stats_lbl")
        self.line_23 = QtWidgets.QFrame(self.group_player6)
        self.line_23.setGeometry(QtCore.QRect(50, 70, 20, 100))
        self.line_23.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.line_24 = QtWidgets.QFrame(self.group_player6)
        self.line_24.setGeometry(QtCore.QRect(0, 60, 220, 20))
        self.line_24.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.lbl_p6_hp_lbl = QtWidgets.QLabel(self.group_player6)
        self.lbl_p6_hp_lbl.setGeometry(QtCore.QRect(70, 80, 47, 20))
        self.lbl_p6_hp_lbl.setObjectName("lbl_p6_hp_lbl")
        self.lbl_p6_ap_lbl = QtWidgets.QLabel(self.group_player6)
        self.lbl_p6_ap_lbl.setGeometry(QtCore.QRect(70, 100, 47, 20))
        self.lbl_p6_ap_lbl.setObjectName("lbl_p6_ap_lbl")
        self.lbl_p6_mana_lbl = QtWidgets.QLabel(self.group_player6)
        self.lbl_p6_mana_lbl.setGeometry(QtCore.QRect(70, 120, 47, 20))
        self.lbl_p6_mana_lbl.setObjectName("lbl_p6_mana_lbl")
        self.lbl_p6_turn_in_lbl = QtWidgets.QLabel(self.group_player6)
        self.lbl_p6_turn_in_lbl.setGeometry(QtCore.QRect(70, 140, 47, 20))
        self.lbl_p6_turn_in_lbl.setObjectName("lbl_p6_turn_in_lbl")
        self.lbl_p6_ap = QtWidgets.QLabel(self.group_player6)
        self.lbl_p6_ap.setGeometry(QtCore.QRect(120, 100, 30, 20))
        self.lbl_p6_ap.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_p6_ap.setObjectName("lbl_p6_ap")
        self.lbl_p6_mana = QtWidgets.QLabel(self.group_player6)
        self.lbl_p6_mana.setGeometry(QtCore.QRect(120, 120, 30, 20))
        self.lbl_p6_mana.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_p6_mana.setObjectName("lbl_p6_mana")
        self.lbl_p6_hp = QtWidgets.QLabel(self.group_player6)
        self.lbl_p6_hp.setGeometry(QtCore.QRect(120, 80, 30, 20))
        self.lbl_p6_hp.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_p6_hp.setObjectName("lbl_p6_hp")
        self.lbl_p6_turn_in = QtWidgets.QLabel(self.group_player6)
        self.lbl_p6_turn_in.setGeometry(QtCore.QRect(120, 140, 30, 20))
        self.lbl_p6_turn_in.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_p6_turn_in.setObjectName("lbl_p6_turn_in")
        self.btn_p6_select = QtWidgets.QPushButton(self.group_player6)
        self.btn_p6_select.setGeometry(QtCore.QRect(170, 80, 40, 40))
        self.btn_p6_select.setObjectName("btn_p6_select")
        self.line_34 = QtWidgets.QFrame(self.group_player6)
        self.line_34.setGeometry(QtCore.QRect(150, 70, 20, 100))
        self.line_34.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_34.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_34.setObjectName("line_34")
        self.btn_p6_info = QtWidgets.QPushButton(self.group_player6)
        self.btn_p6_info.setGeometry(QtCore.QRect(170, 120, 40, 40))
        self.btn_p6_info.setObjectName("btn_p6_info")
        self.group_player4 = QtWidgets.QGroupBox(self.GameMenuWidget)
        self.group_player4.setGeometry(QtCore.QRect(410, 310, 220, 170))
        self.group_player4.setObjectName("group_player4")
        self.lbl_p4_name_lbl = QtWidgets.QLabel(self.group_player4)
        self.lbl_p4_name_lbl.setGeometry(QtCore.QRect(10, 20, 80, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p4_name_lbl.setFont(font)
        self.lbl_p4_name_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p4_name_lbl.setObjectName("lbl_p4_name_lbl")
        self.lbl_p4_name = QtWidgets.QLabel(self.group_player4)
        self.lbl_p4_name.setGeometry(QtCore.QRect(100, 20, 120, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lbl_p4_name.setFont(font)
        self.lbl_p4_name.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p4_name.setObjectName("lbl_p4_name")
        self.lbl_p4_profession = QtWidgets.QLabel(self.group_player4)
        self.lbl_p4_profession.setGeometry(QtCore.QRect(100, 40, 120, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lbl_p4_profession.setFont(font)
        self.lbl_p4_profession.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p4_profession.setObjectName("lbl_p4_profession")
        self.lbl_p4_profession_lbl = QtWidgets.QLabel(self.group_player4)
        self.lbl_p4_profession_lbl.setGeometry(QtCore.QRect(10, 40, 80, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p4_profession_lbl.setFont(font)
        self.lbl_p4_profession_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p4_profession_lbl.setObjectName("lbl_p4_profession_lbl")
        self.lbl_p4_stats_lbl = QtWidgets.QLabel(self.group_player4)
        self.lbl_p4_stats_lbl.setGeometry(QtCore.QRect(10, 100, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p4_stats_lbl.setFont(font)
        self.lbl_p4_stats_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p4_stats_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_p4_stats_lbl.setObjectName("lbl_p4_stats_lbl")
        self.line_25 = QtWidgets.QFrame(self.group_player4)
        self.line_25.setGeometry(QtCore.QRect(50, 70, 20, 100))
        self.line_25.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.line_26 = QtWidgets.QFrame(self.group_player4)
        self.line_26.setGeometry(QtCore.QRect(0, 60, 220, 20))
        self.line_26.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.lbl_p4_hp_lbl = QtWidgets.QLabel(self.group_player4)
        self.lbl_p4_hp_lbl.setGeometry(QtCore.QRect(70, 80, 47, 20))
        self.lbl_p4_hp_lbl.setObjectName("lbl_p4_hp_lbl")
        self.lbl_p4_ap_lbl = QtWidgets.QLabel(self.group_player4)
        self.lbl_p4_ap_lbl.setGeometry(QtCore.QRect(70, 100, 47, 20))
        self.lbl_p4_ap_lbl.setObjectName("lbl_p4_ap_lbl")
        self.lbl_p4_mana_lbl = QtWidgets.QLabel(self.group_player4)
        self.lbl_p4_mana_lbl.setGeometry(QtCore.QRect(70, 120, 47, 20))
        self.lbl_p4_mana_lbl.setObjectName("lbl_p4_mana_lbl")
        self.lbl_p4_turn_in_lbl = QtWidgets.QLabel(self.group_player4)
        self.lbl_p4_turn_in_lbl.setGeometry(QtCore.QRect(70, 140, 47, 20))
        self.lbl_p4_turn_in_lbl.setObjectName("lbl_p4_turn_in_lbl")
        self.lbl_p4_ap = QtWidgets.QLabel(self.group_player4)
        self.lbl_p4_ap.setGeometry(QtCore.QRect(110, 100, 40, 20))
        self.lbl_p4_ap.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_p4_ap.setObjectName("lbl_p4_ap")
        self.lbl_p4_mana = QtWidgets.QLabel(self.group_player4)
        self.lbl_p4_mana.setGeometry(QtCore.QRect(110, 120, 40, 20))
        self.lbl_p4_mana.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_p4_mana.setObjectName("lbl_p4_mana")
        self.lbl_p4_hp = QtWidgets.QLabel(self.group_player4)
        self.lbl_p4_hp.setGeometry(QtCore.QRect(110, 80, 40, 20))
        self.lbl_p4_hp.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_p4_hp.setObjectName("lbl_p4_hp")
        self.lbl_p4_turn_in = QtWidgets.QLabel(self.group_player4)
        self.lbl_p4_turn_in.setGeometry(QtCore.QRect(110, 140, 40, 20))
        self.lbl_p4_turn_in.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_p4_turn_in.setObjectName("lbl_p4_turn_in")
        self.btn_p4_select = QtWidgets.QPushButton(self.group_player4)
        self.btn_p4_select.setGeometry(QtCore.QRect(170, 80, 40, 40))
        self.btn_p4_select.setObjectName("btn_p4_select")
        self.line_6 = QtWidgets.QFrame(self.group_player4)
        self.line_6.setGeometry(QtCore.QRect(150, 70, 20, 100))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.btn_p4_info = QtWidgets.QPushButton(self.group_player4)
        self.btn_p4_info.setGeometry(QtCore.QRect(170, 120, 40, 40))
        self.btn_p4_info.setObjectName("btn_p4_info")
        self.line_27 = QtWidgets.QFrame(self.GameMenuWidget)
        self.line_27.setGeometry(QtCore.QRect(0, 610, 390, 20))
        self.line_27.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.line_28 = QtWidgets.QFrame(self.GameMenuWidget)
        self.line_28.setGeometry(QtCore.QRect(390, 490, 780, 20))
        self.line_28.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_28.setObjectName("line_28")
        self.lbl_connected_ip_lbl = QtWidgets.QLabel(self.GameMenuWidget)
        self.lbl_connected_ip_lbl.setGeometry(QtCore.QRect(410, 20, 140, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lbl_connected_ip_lbl.setFont(font)
        self.lbl_connected_ip_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_connected_ip_lbl.setObjectName("lbl_connected_ip_lbl")
        self.lbl_connected_ip = QtWidgets.QLabel(self.GameMenuWidget)
        self.lbl_connected_ip.setGeometry(QtCore.QRect(560, 20, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lbl_connected_ip.setFont(font)
        self.lbl_connected_ip.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_connected_ip.setObjectName("lbl_connected_ip")
        self.line_29 = QtWidgets.QFrame(self.GameMenuWidget)
        self.line_29.setGeometry(QtCore.QRect(720, 0, 20, 90))
        self.line_29.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_29.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_29.setObjectName("line_29")
        self.lbl_turn_number_lbl = QtWidgets.QLabel(self.GameMenuWidget)
        self.lbl_turn_number_lbl.setGeometry(QtCore.QRect(750, 20, 120, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lbl_turn_number_lbl.setFont(font)
        self.lbl_turn_number_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_turn_number_lbl.setObjectName("lbl_turn_number_lbl")
        self.lbl_turn_number = QtWidgets.QLabel(self.GameMenuWidget)
        self.lbl_turn_number.setGeometry(QtCore.QRect(880, 20, 40, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lbl_turn_number.setFont(font)
        self.lbl_turn_number.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_turn_number.setObjectName("lbl_turn_number")
        self.line_30 = QtWidgets.QFrame(self.GameMenuWidget)
        self.line_30.setGeometry(QtCore.QRect(930, 0, 20, 90))
        self.line_30.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_30.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_30.setObjectName("line_30")
        self.lbl_active_player_number = QtWidgets.QLabel(self.GameMenuWidget)
        self.lbl_active_player_number.setGeometry(QtCore.QRect(1110, 20, 40, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lbl_active_player_number.setFont(font)
        self.lbl_active_player_number.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_active_player_number.setObjectName("lbl_active_player_number")
        self.lbl_active_player_number_lbl = QtWidgets.QLabel(self.GameMenuWidget)
        self.lbl_active_player_number_lbl.setGeometry(QtCore.QRect(960, 20, 140, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lbl_active_player_number_lbl.setFont(font)
        self.lbl_active_player_number_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_active_player_number_lbl.setObjectName("lbl_active_player_number_lbl")
        self.line_31 = QtWidgets.QFrame(self.GameMenuWidget)
        self.line_31.setGeometry(QtCore.QRect(640, 90, 20, 410))
        self.line_31.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_31.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_31.setObjectName("line_31")
        self.line_32 = QtWidgets.QFrame(self.GameMenuWidget)
        self.line_32.setGeometry(QtCore.QRect(900, 90, 20, 410))
        self.line_32.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_32.setObjectName("line_32")
        self.line_33 = QtWidgets.QFrame(self.GameMenuWidget)
        self.line_33.setGeometry(QtCore.QRect(390, 290, 780, 20))
        self.line_33.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_33.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_33.setObjectName("line_33")
        self.list_actions = QtWidgets.QListWidget(self.GameMenuWidget)
        self.list_actions.setGeometry(QtCore.QRect(410, 560, 220, 180))
        self.list_actions.setObjectName("list_actions")
        self.list_subactions = QtWidgets.QListWidget(self.GameMenuWidget)
        self.list_subactions.setGeometry(QtCore.QRect(670, 560, 220, 180))
        self.list_subactions.setObjectName("list_subactions")
        self.btn_do_selected_action = QtWidgets.QPushButton(self.GameMenuWidget)
        self.btn_do_selected_action.setGeometry(QtCore.QRect(930, 580, 100, 70))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_do_selected_action.setFont(font)
        self.btn_do_selected_action.setObjectName("btn_do_selected_action")
        self.btn_end_turn = QtWidgets.QPushButton(self.GameMenuWidget)
        self.btn_end_turn.setGeometry(QtCore.QRect(930, 670, 220, 70))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_end_turn.setFont(font)
        self.btn_end_turn.setObjectName("btn_end_turn")
        self.btn_action_info = QtWidgets.QPushButton(self.GameMenuWidget)
        self.btn_action_info.setGeometry(QtCore.QRect(1050, 580, 100, 70))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_action_info.setFont(font)
        self.btn_action_info.setObjectName("btn_action_info")
        self.lbl_selected_target_lbl = QtWidgets.QLabel(self.GameMenuWidget)
        self.lbl_selected_target_lbl.setGeometry(QtCore.QRect(930, 520, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_selected_target_lbl.setFont(font)
        self.lbl_selected_target_lbl.setObjectName("lbl_selected_target_lbl")
        self.lbl_selected_target = QtWidgets.QLabel(self.GameMenuWidget)
        self.lbl_selected_target.setGeometry(QtCore.QRect(1080, 520, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_selected_target.setFont(font)
        self.lbl_selected_target.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_selected_target.setObjectName("lbl_selected_target")
        self.lbl_actions = QtWidgets.QLabel(self.GameMenuWidget)
        self.lbl_actions.setGeometry(QtCore.QRect(440, 510, 160, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_actions.setFont(font)
        self.lbl_actions.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_actions.setObjectName("lbl_actions")
        self.lbl_sub_actions = QtWidgets.QLabel(self.GameMenuWidget)
        self.lbl_sub_actions.setGeometry(QtCore.QRect(700, 510, 160, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_sub_actions.setFont(font)
        self.lbl_sub_actions.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_sub_actions.setObjectName("lbl_sub_actions")
        TPRGameMenu.setCentralWidget(self.GameMenuWidget)

        self.retranslateUi(TPRGameMenu)
        QtCore.QMetaObject.connectSlotsByName(TPRGameMenu)

    def retranslateUi(self, TPRGameMenu):
        _translate = QtCore.QCoreApplication.translate
        TPRGameMenu.setWindowTitle(_translate("TPRGameMenu", "MainWindow"))
        self.btn_clear_log.setText(_translate("TPRGameMenu", "Clear Log"))
        self.btn_send_message.setText(_translate("TPRGameMenu", "Send Message"))
        self.lbl_title.setText(_translate("TPRGameMenu", "Tiny PyRPG Game Menu"))
        self.txt_messagebox.setPlaceholderText(_translate("TPRGameMenu", "Send a message..."))
        self.group_player1.setTitle(_translate("TPRGameMenu", "Player 1"))
        self.lbl_p1_name_lbl.setText(_translate("TPRGameMenu", "Name"))
        self.lbl_p1_name.setText(_translate("TPRGameMenu", "Player 1 Name"))
        self.lbl_p1_profession.setText(_translate("TPRGameMenu", "Player 1 Profession"))
        self.lbl_p1_profession_lbl.setText(_translate("TPRGameMenu", "Profession"))
        self.lbl_p1_stats_lbl.setText(_translate("TPRGameMenu", "Stats"))
        self.lbl_p1_hp_lbl.setText(_translate("TPRGameMenu", "HP:"))
        self.lbl_p1_ap_lbl.setText(_translate("TPRGameMenu", "AP:"))
        self.lbl_p1_mana_lbl.setText(_translate("TPRGameMenu", "Mana:"))
        self.lbl_p1_turn_in_lbl.setText(_translate("TPRGameMenu", "Turn In:"))
        self.lbl_p1_ap.setText(_translate("TPRGameMenu", "99/99"))
        self.lbl_p1_mana.setText(_translate("TPRGameMenu", "99/99"))
        self.lbl_p1_hp.setText(_translate("TPRGameMenu", "99/99"))
        self.lbl_p1_turn_in.setText(_translate("TPRGameMenu", "now"))
        self.btn_p1_select.setText(_translate("TPRGameMenu", "P1"))
        self.btn_p1_info.setText(_translate("TPRGameMenu", "Info"))
        self.group_player2.setTitle(_translate("TPRGameMenu", "Player 2"))
        self.lbl_p2_name_lbl.setText(_translate("TPRGameMenu", "Name"))
        self.lbl_p2_name.setText(_translate("TPRGameMenu", "Player 2 Name"))
        self.lbl_p2_profession.setText(_translate("TPRGameMenu", "Player 2 Profession"))
        self.lbl_p2_profession_lbl.setText(_translate("TPRGameMenu", "Profession"))
        self.lbl_p2_stats_lbl.setText(_translate("TPRGameMenu", "Stats"))
        self.lbl_p2_hp_lbl.setText(_translate("TPRGameMenu", "HP:"))
        self.lbl_p2_ap_lbl.setText(_translate("TPRGameMenu", "AP:"))
        self.lbl_p2_mana_lbl.setText(_translate("TPRGameMenu", "Mana:"))
        self.lbl_p2_turn_in_lbl.setText(_translate("TPRGameMenu", "Turn In:"))
        self.lbl_p2_ap.setText(_translate("TPRGameMenu", "99/99"))
        self.lbl_p2_mana.setText(_translate("TPRGameMenu", "99/99"))
        self.lbl_p2_hp.setText(_translate("TPRGameMenu", "99/99"))
        self.lbl_p2_turn_in.setText(_translate("TPRGameMenu", "now"))
        self.btn_p2_select.setText(_translate("TPRGameMenu", "P2"))
        self.btn_p2_info.setText(_translate("TPRGameMenu", "Info"))
        self.group_player3.setTitle(_translate("TPRGameMenu", "Player 3"))
        self.lbl_p3_name_lbl.setText(_translate("TPRGameMenu", "Name"))
        self.lbl_p3_name.setText(_translate("TPRGameMenu", "Player 3 Name"))
        self.lbl_p3_profession.setText(_translate("TPRGameMenu", "Player 3 Profession"))
        self.lbl_p3_profession_lbl.setText(_translate("TPRGameMenu", "Profession"))
        self.lbl_p3_stats_lbl.setText(_translate("TPRGameMenu", "Stats"))
        self.lbl_p3_hp_lbl.setText(_translate("TPRGameMenu", "HP:"))
        self.lbl_p3_ap_lbl.setText(_translate("TPRGameMenu", "AP:"))
        self.lbl_p3_mana_lbl.setText(_translate("TPRGameMenu", "Mana:"))
        self.lbl_p3_turn_in_lbl.setText(_translate("TPRGameMenu", "Turn In:"))
        self.lbl_p3_ap.setText(_translate("TPRGameMenu", "99/99"))
        self.lbl_p3_mana.setText(_translate("TPRGameMenu", "99/99"))
        self.lbl_p3_hp.setText(_translate("TPRGameMenu", "99/99"))
        self.lbl_p3_turn_in.setText(_translate("TPRGameMenu", "now"))
        self.btn_p3_select.setText(_translate("TPRGameMenu", "P3"))
        self.btn_p3_info.setText(_translate("TPRGameMenu", "Info"))
        self.group_player5.setTitle(_translate("TPRGameMenu", "Player 5"))
        self.lbl_p5_name_lbl.setText(_translate("TPRGameMenu", "Name"))
        self.lbl_p5_name.setText(_translate("TPRGameMenu", "Player 5 Name"))
        self.lbl_p5_profession.setText(_translate("TPRGameMenu", "Player 5 Profession"))
        self.lbl_p5_profession_lbl.setText(_translate("TPRGameMenu", "Profession"))
        self.lbl_p5_stats_lbl.setText(_translate("TPRGameMenu", "Stats"))
        self.lbl_p5_hp_lbl.setText(_translate("TPRGameMenu", "HP:"))
        self.lbl_p5_ap_lbl.setText(_translate("TPRGameMenu", "AP:"))
        self.lbl_p5_mana_lbl.setText(_translate("TPRGameMenu", "Mana:"))
        self.lbl_p5_turn_in_lbl.setText(_translate("TPRGameMenu", "Turn In:"))
        self.lbl_p5_ap.setText(_translate("TPRGameMenu", "99/99"))
        self.lbl_p5_mana.setText(_translate("TPRGameMenu", "99/99"))
        self.lbl_p5_hp.setText(_translate("TPRGameMenu", "99/99"))
        self.lbl_p5_turn_in.setText(_translate("TPRGameMenu", "now"))
        self.btn_p5_select.setText(_translate("TPRGameMenu", "P5"))
        self.btn_p5_info.setText(_translate("TPRGameMenu", "Info"))
        self.group_player6.setTitle(_translate("TPRGameMenu", "Player 6"))
        self.lbl_p6_name_lbl.setText(_translate("TPRGameMenu", "Name"))
        self.lbl_p6_name.setText(_translate("TPRGameMenu", "Player 6 Name"))
        self.lbl_p6_profession.setText(_translate("TPRGameMenu", "Player 6 Profession"))
        self.lbl_p6_profession_lbl.setText(_translate("TPRGameMenu", "Profession"))
        self.lbl_p6_stats_lbl.setText(_translate("TPRGameMenu", "Stats"))
        self.lbl_p6_hp_lbl.setText(_translate("TPRGameMenu", "HP:"))
        self.lbl_p6_ap_lbl.setText(_translate("TPRGameMenu", "AP:"))
        self.lbl_p6_mana_lbl.setText(_translate("TPRGameMenu", "Mana:"))
        self.lbl_p6_turn_in_lbl.setText(_translate("TPRGameMenu", "Turn In:"))
        self.lbl_p6_ap.setText(_translate("TPRGameMenu", "99/99"))
        self.lbl_p6_mana.setText(_translate("TPRGameMenu", "99/99"))
        self.lbl_p6_hp.setText(_translate("TPRGameMenu", "99/99"))
        self.lbl_p6_turn_in.setText(_translate("TPRGameMenu", "now"))
        self.btn_p6_select.setText(_translate("TPRGameMenu", "P6"))
        self.btn_p6_info.setText(_translate("TPRGameMenu", "Info"))
        self.group_player4.setTitle(_translate("TPRGameMenu", "Player 4"))
        self.lbl_p4_name_lbl.setText(_translate("TPRGameMenu", "Name"))
        self.lbl_p4_name.setText(_translate("TPRGameMenu", "Player 4 Name"))
        self.lbl_p4_profession.setText(_translate("TPRGameMenu", "Player 4 Profession"))
        self.lbl_p4_profession_lbl.setText(_translate("TPRGameMenu", "Profession"))
        self.lbl_p4_stats_lbl.setText(_translate("TPRGameMenu", "Stats"))
        self.lbl_p4_hp_lbl.setText(_translate("TPRGameMenu", "HP:"))
        self.lbl_p4_ap_lbl.setText(_translate("TPRGameMenu", "AP:"))
        self.lbl_p4_mana_lbl.setText(_translate("TPRGameMenu", "Mana:"))
        self.lbl_p4_turn_in_lbl.setText(_translate("TPRGameMenu", "Turn In:"))
        self.lbl_p4_ap.setText(_translate("TPRGameMenu", "99/99"))
        self.lbl_p4_mana.setText(_translate("TPRGameMenu", "99/99"))
        self.lbl_p4_hp.setText(_translate("TPRGameMenu", "99/99"))
        self.lbl_p4_turn_in.setText(_translate("TPRGameMenu", "now"))
        self.btn_p4_select.setText(_translate("TPRGameMenu", "P4"))
        self.btn_p4_info.setText(_translate("TPRGameMenu", "Info"))
        self.lbl_connected_ip_lbl.setText(_translate("TPRGameMenu", "Connected To:"))
        self.lbl_connected_ip.setText(_translate("TPRGameMenu", "192.168.100.100"))
        self.lbl_turn_number_lbl.setText(_translate("TPRGameMenu", "Turn Number:"))
        self.lbl_turn_number.setText(_translate("TPRGameMenu", "999"))
        self.lbl_active_player_number.setText(_translate("TPRGameMenu", "1"))
        self.lbl_active_player_number_lbl.setText(_translate("TPRGameMenu", "Player Number:"))
        self.btn_do_selected_action.setText(_translate("TPRGameMenu", "Action"))
        self.btn_end_turn.setText(_translate("TPRGameMenu", "End Turn"))
        self.btn_action_info.setText(_translate("TPRGameMenu", "Info"))
        self.lbl_selected_target_lbl.setText(_translate("TPRGameMenu", "Selected Target:"))
        self.lbl_selected_target.setText(_translate("TPRGameMenu", "P1"))
        self.lbl_actions.setText(_translate("TPRGameMenu", "Actions"))
        self.lbl_sub_actions.setText(_translate("TPRGameMenu", "Sub-Actions"))
