# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Jeffrey Smith\Desktop\game.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1253, 884)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.text_log = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.text_log.setGeometry(QtCore.QRect(40, 80, 301, 431))
        self.text_log.setObjectName("text_log")
        self.enemy_pic_1 = QtWidgets.QLabel(self.centralwidget)
        self.enemy_pic_1.setGeometry(QtCore.QRect(550, 110, 100, 80))
        self.enemy_pic_1.setObjectName("enemy_pic_1")
        self.enemy_pic_2 = QtWidgets.QLabel(self.centralwidget)
        self.enemy_pic_2.setGeometry(QtCore.QRect(710, 110, 100, 80))
        self.enemy_pic_2.setObjectName("enemy_pic_2")
        self.enemy_pic_3 = QtWidgets.QLabel(self.centralwidget)
        self.enemy_pic_3.setGeometry(QtCore.QRect(870, 110, 100, 80))
        self.enemy_pic_3.setObjectName("enemy_pic_3")
        self.team_pic_1 = QtWidgets.QLabel(self.centralwidget)
        self.team_pic_1.setGeometry(QtCore.QRect(550, 220, 100, 80))
        self.team_pic_1.setObjectName("team_pic_1")
        self.team_pic_2 = QtWidgets.QLabel(self.centralwidget)
        self.team_pic_2.setGeometry(QtCore.QRect(710, 220, 100, 80))
        self.team_pic_2.setObjectName("team_pic_2")
        self.team_pic_3 = QtWidgets.QLabel(self.centralwidget)
        self.team_pic_3.setGeometry(QtCore.QRect(870, 220, 100, 80))
        self.team_pic_3.setObjectName("team_pic_3")
        self.hp_bar = QtWidgets.QProgressBar(self.centralwidget)
        self.hp_bar.setGeometry(QtCore.QRect(640, 410, 321, 41))
        self.hp_bar.setProperty("value", 100)
        self.hp_bar.setObjectName("hp_bar")
        self.mana_bar = QtWidgets.QProgressBar(self.centralwidget)
        self.mana_bar.setGeometry(QtCore.QRect(640, 460, 321, 41))
        self.mana_bar.setProperty("value", 100)
        self.mana_bar.setObjectName("mana_bar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(540, 410, 91, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(540, 470, 81, 31))
        self.label_2.setObjectName("label_2")
        self.item_list = QtWidgets.QListWidget(self.centralwidget)
        self.item_list.setGeometry(QtCore.QRect(70, 570, 256, 192))
        self.item_list.setObjectName("item_list")
        item = QtWidgets.QListWidgetItem()
        self.item_list.addItem(item)
        self.action_button = QtWidgets.QPushButton(self.centralwidget)
        self.action_button.setGeometry(QtCore.QRect(620, 640, 121, 61))
        self.action_button.setObjectName("action_button")
        self.mystery_button = QtWidgets.QPushButton(self.centralwidget)
        self.mystery_button.setGeometry(QtCore.QRect(810, 640, 121, 61))
        self.mystery_button.setObjectName("mystery_button")
        self.end_turn_button = QtWidgets.QPushButton(self.centralwidget)
        self.end_turn_button.setGeometry(QtCore.QRect(620, 720, 311, 91))
        self.end_turn_button.setObjectName("end_turn_button")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(660, 580, 81, 41))
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setProperty("value", 500.0)
        self.lcdNumber.setObjectName("lcdNumber")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(580, 580, 71, 41))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1253, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.enemy_pic_1.setText(_translate("MainWindow", "TextLabel"))
        self.enemy_pic_2.setText(_translate("MainWindow", "TextLabel"))
        self.enemy_pic_3.setText(_translate("MainWindow", "TextLabel"))
        self.team_pic_1.setText(_translate("MainWindow", "TextLabel"))
        self.team_pic_2.setText(_translate("MainWindow", "TextLabel"))
        self.team_pic_3.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "Health Points"))
        self.label_2.setText(_translate("MainWindow", "mana"))
        __sortingEnabled = self.item_list.isSortingEnabled()
        self.item_list.setSortingEnabled(False)
        item = self.item_list.item(0)
        item.setText(_translate("MainWindow", "This is for items"))
        self.item_list.setSortingEnabled(__sortingEnabled)
        self.action_button.setText(_translate("MainWindow", "Action"))
        self.mystery_button.setText(_translate("MainWindow", "Dont know what this is"))
        self.end_turn_button.setText(_translate("MainWindow", "End Turn"))
        self.label_3.setText(_translate("MainWindow", "AP points"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

