# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/lobby-menu.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TPRLobbyMenu(object):
    def setupUi(self, TPRLobbyMenu):
        TPRLobbyMenu.setObjectName("TPRLobbyMenu")
        TPRLobbyMenu.resize(800, 605)
        self.LobbyMenuWidget = QtWidgets.QWidget(TPRLobbyMenu)
        self.LobbyMenuWidget.setObjectName("LobbyMenuWidget")
        self.line = QtWidgets.QFrame(self.LobbyMenuWidget)
        self.line.setGeometry(QtCore.QRect(260, 0, 20, 601))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.LobbyMenuWidget)
        self.line_2.setGeometry(QtCore.QRect(0, 510, 801, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.LobbyMenuWidget)
        self.line_3.setGeometry(QtCore.QRect(0, 250, 271, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.lbl_title = QtWidgets.QLabel(self.LobbyMenuWidget)
        self.lbl_title.setGeometry(QtCore.QRect(20, 20, 231, 221))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.lbl_title.setFont(font)
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setObjectName("lbl_title")
        self.lbl_connected_ip_lbl = QtWidgets.QLabel(self.LobbyMenuWidget)
        self.lbl_connected_ip_lbl.setGeometry(QtCore.QRect(50, 530, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_connected_ip_lbl.setFont(font)
        self.lbl_connected_ip_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_connected_ip_lbl.setObjectName("lbl_connected_ip_lbl")
        self.lbl_connected_ip = QtWidgets.QLabel(self.LobbyMenuWidget)
        self.lbl_connected_ip.setGeometry(QtCore.QRect(50, 560, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(False)
        self.lbl_connected_ip.setFont(font)
        self.lbl_connected_ip.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_connected_ip.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_connected_ip.setObjectName("lbl_connected_ip")
        self.group_player1 = QtWidgets.QGroupBox(self.LobbyMenuWidget)
        self.group_player1.setGeometry(QtCore.QRect(290, 20, 151, 231))
        self.group_player1.setObjectName("group_player1")
        self.lbl_p1_name_lbl = QtWidgets.QLabel(self.group_player1)
        self.lbl_p1_name_lbl.setGeometry(QtCore.QRect(10, 20, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p1_name_lbl.setFont(font)
        self.lbl_p1_name_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p1_name_lbl.setObjectName("lbl_p1_name_lbl")
        self.lbl_p1_name = QtWidgets.QLabel(self.group_player1)
        self.lbl_p1_name.setGeometry(QtCore.QRect(10, 40, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lbl_p1_name.setFont(font)
        self.lbl_p1_name.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p1_name.setObjectName("lbl_p1_name")
        self.lbl_p1_profession = QtWidgets.QLabel(self.group_player1)
        self.lbl_p1_profession.setGeometry(QtCore.QRect(10, 80, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lbl_p1_profession.setFont(font)
        self.lbl_p1_profession.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p1_profession.setObjectName("lbl_p1_profession")
        self.lbl_p1_profession_lbl = QtWidgets.QLabel(self.group_player1)
        self.lbl_p1_profession_lbl.setGeometry(QtCore.QRect(10, 60, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p1_profession_lbl.setFont(font)
        self.lbl_p1_profession_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p1_profession_lbl.setObjectName("lbl_p1_profession_lbl")
        self.lbl_p1_profession_dsc_lbl = QtWidgets.QLabel(self.group_player1)
        self.lbl_p1_profession_dsc_lbl.setGeometry(QtCore.QRect(10, 100, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p1_profession_dsc_lbl.setFont(font)
        self.lbl_p1_profession_dsc_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p1_profession_dsc_lbl.setObjectName("lbl_p1_profession_dsc_lbl")
        self.lbl_p1_profession_dsc = QtWidgets.QLabel(self.group_player1)
        self.lbl_p1_profession_dsc.setGeometry(QtCore.QRect(10, 120, 131, 80))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.lbl_p1_profession_dsc.setFont(font)
        self.lbl_p1_profession_dsc.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p1_profession_dsc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_p1_profession_dsc.setWordWrap(True)
        self.lbl_p1_profession_dsc.setObjectName("lbl_p1_profession_dsc")
        self.lbl_p1_ready_lbl = QtWidgets.QLabel(self.group_player1)
        self.lbl_p1_ready_lbl.setGeometry(QtCore.QRect(10, 200, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p1_ready_lbl.setFont(font)
        self.lbl_p1_ready_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p1_ready_lbl.setObjectName("lbl_p1_ready_lbl")
        self.lbl_p1_ready = QtWidgets.QLabel(self.group_player1)
        self.lbl_p1_ready.setGeometry(QtCore.QRect(110, 200, 30, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lbl_p1_ready.setFont(font)
        self.lbl_p1_ready.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p1_ready.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_p1_ready.setObjectName("lbl_p1_ready")
        self.group_player2 = QtWidgets.QGroupBox(self.LobbyMenuWidget)
        self.group_player2.setGeometry(QtCore.QRect(460, 20, 150, 231))
        self.group_player2.setObjectName("group_player2")
        self.lbl_p2_profession_lbl = QtWidgets.QLabel(self.group_player2)
        self.lbl_p2_profession_lbl.setGeometry(QtCore.QRect(10, 60, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p2_profession_lbl.setFont(font)
        self.lbl_p2_profession_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p2_profession_lbl.setObjectName("lbl_p2_profession_lbl")
        self.lbl_p2_profession_dsc = QtWidgets.QLabel(self.group_player2)
        self.lbl_p2_profession_dsc.setGeometry(QtCore.QRect(10, 120, 131, 80))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.lbl_p2_profession_dsc.setFont(font)
        self.lbl_p2_profession_dsc.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p2_profession_dsc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_p2_profession_dsc.setWordWrap(True)
        self.lbl_p2_profession_dsc.setObjectName("lbl_p2_profession_dsc")
        self.lbl_p2_name = QtWidgets.QLabel(self.group_player2)
        self.lbl_p2_name.setGeometry(QtCore.QRect(10, 40, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lbl_p2_name.setFont(font)
        self.lbl_p2_name.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p2_name.setObjectName("lbl_p2_name")
        self.lbl_p2_profession_dsc_lbl = QtWidgets.QLabel(self.group_player2)
        self.lbl_p2_profession_dsc_lbl.setGeometry(QtCore.QRect(10, 100, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p2_profession_dsc_lbl.setFont(font)
        self.lbl_p2_profession_dsc_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p2_profession_dsc_lbl.setObjectName("lbl_p2_profession_dsc_lbl")
        self.lbl_p2_name_lbl = QtWidgets.QLabel(self.group_player2)
        self.lbl_p2_name_lbl.setGeometry(QtCore.QRect(10, 20, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p2_name_lbl.setFont(font)
        self.lbl_p2_name_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p2_name_lbl.setObjectName("lbl_p2_name_lbl")
        self.lbl_p2_profession = QtWidgets.QLabel(self.group_player2)
        self.lbl_p2_profession.setGeometry(QtCore.QRect(10, 80, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lbl_p2_profession.setFont(font)
        self.lbl_p2_profession.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p2_profession.setObjectName("lbl_p2_profession")
        self.lbl_p2_ready_lbl = QtWidgets.QLabel(self.group_player2)
        self.lbl_p2_ready_lbl.setGeometry(QtCore.QRect(10, 200, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p2_ready_lbl.setFont(font)
        self.lbl_p2_ready_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p2_ready_lbl.setObjectName("lbl_p2_ready_lbl")
        self.lbl_p2_ready = QtWidgets.QLabel(self.group_player2)
        self.lbl_p2_ready.setGeometry(QtCore.QRect(110, 200, 30, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lbl_p2_ready.setFont(font)
        self.lbl_p2_ready.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p2_ready.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_p2_ready.setObjectName("lbl_p2_ready")
        self.group_player3 = QtWidgets.QGroupBox(self.LobbyMenuWidget)
        self.group_player3.setGeometry(QtCore.QRect(630, 20, 150, 231))
        self.group_player3.setObjectName("group_player3")
        self.lbl_p3_profession_lbl = QtWidgets.QLabel(self.group_player3)
        self.lbl_p3_profession_lbl.setGeometry(QtCore.QRect(10, 60, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p3_profession_lbl.setFont(font)
        self.lbl_p3_profession_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p3_profession_lbl.setObjectName("lbl_p3_profession_lbl")
        self.lbl_p3_profession_dsc = QtWidgets.QLabel(self.group_player3)
        self.lbl_p3_profession_dsc.setGeometry(QtCore.QRect(10, 120, 131, 80))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.lbl_p3_profession_dsc.setFont(font)
        self.lbl_p3_profession_dsc.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p3_profession_dsc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_p3_profession_dsc.setWordWrap(True)
        self.lbl_p3_profession_dsc.setObjectName("lbl_p3_profession_dsc")
        self.lbl_p3_name = QtWidgets.QLabel(self.group_player3)
        self.lbl_p3_name.setGeometry(QtCore.QRect(10, 40, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lbl_p3_name.setFont(font)
        self.lbl_p3_name.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p3_name.setObjectName("lbl_p3_name")
        self.lbl_p3_profession_dsc_lbl = QtWidgets.QLabel(self.group_player3)
        self.lbl_p3_profession_dsc_lbl.setGeometry(QtCore.QRect(10, 100, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p3_profession_dsc_lbl.setFont(font)
        self.lbl_p3_profession_dsc_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p3_profession_dsc_lbl.setObjectName("lbl_p3_profession_dsc_lbl")
        self.lbl_p3_name_lbl = QtWidgets.QLabel(self.group_player3)
        self.lbl_p3_name_lbl.setGeometry(QtCore.QRect(10, 20, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p3_name_lbl.setFont(font)
        self.lbl_p3_name_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p3_name_lbl.setObjectName("lbl_p3_name_lbl")
        self.lbl_p3_profession = QtWidgets.QLabel(self.group_player3)
        self.lbl_p3_profession.setGeometry(QtCore.QRect(10, 80, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lbl_p3_profession.setFont(font)
        self.lbl_p3_profession.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p3_profession.setObjectName("lbl_p3_profession")
        self.lbl_p3_ready_lbl = QtWidgets.QLabel(self.group_player3)
        self.lbl_p3_ready_lbl.setGeometry(QtCore.QRect(10, 200, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p3_ready_lbl.setFont(font)
        self.lbl_p3_ready_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p3_ready_lbl.setObjectName("lbl_p3_ready_lbl")
        self.lbl_p3_ready = QtWidgets.QLabel(self.group_player3)
        self.lbl_p3_ready.setGeometry(QtCore.QRect(110, 200, 30, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lbl_p3_ready.setFont(font)
        self.lbl_p3_ready.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p3_ready.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_p3_ready.setObjectName("lbl_p3_ready")
        self.group_player6 = QtWidgets.QGroupBox(self.LobbyMenuWidget)
        self.group_player6.setGeometry(QtCore.QRect(630, 270, 150, 231))
        self.group_player6.setObjectName("group_player6")
        self.lbl_p6_profession_lbl = QtWidgets.QLabel(self.group_player6)
        self.lbl_p6_profession_lbl.setGeometry(QtCore.QRect(10, 60, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p6_profession_lbl.setFont(font)
        self.lbl_p6_profession_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p6_profession_lbl.setObjectName("lbl_p6_profession_lbl")
        self.lbl_p6_profession_dsc = QtWidgets.QLabel(self.group_player6)
        self.lbl_p6_profession_dsc.setGeometry(QtCore.QRect(10, 120, 131, 80))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.lbl_p6_profession_dsc.setFont(font)
        self.lbl_p6_profession_dsc.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p6_profession_dsc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_p6_profession_dsc.setWordWrap(True)
        self.lbl_p6_profession_dsc.setObjectName("lbl_p6_profession_dsc")
        self.lbl_p6_name = QtWidgets.QLabel(self.group_player6)
        self.lbl_p6_name.setGeometry(QtCore.QRect(10, 40, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lbl_p6_name.setFont(font)
        self.lbl_p6_name.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p6_name.setObjectName("lbl_p6_name")
        self.lbl_p6_profession_dsc_lbl = QtWidgets.QLabel(self.group_player6)
        self.lbl_p6_profession_dsc_lbl.setGeometry(QtCore.QRect(10, 100, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p6_profession_dsc_lbl.setFont(font)
        self.lbl_p6_profession_dsc_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p6_profession_dsc_lbl.setObjectName("lbl_p6_profession_dsc_lbl")
        self.lbl_p6_name_lbl = QtWidgets.QLabel(self.group_player6)
        self.lbl_p6_name_lbl.setGeometry(QtCore.QRect(10, 20, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p6_name_lbl.setFont(font)
        self.lbl_p6_name_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p6_name_lbl.setObjectName("lbl_p6_name_lbl")
        self.lbl_p6_profession = QtWidgets.QLabel(self.group_player6)
        self.lbl_p6_profession.setGeometry(QtCore.QRect(10, 80, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lbl_p6_profession.setFont(font)
        self.lbl_p6_profession.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p6_profession.setObjectName("lbl_p6_profession")
        self.lbl_p6_ready_lbl = QtWidgets.QLabel(self.group_player6)
        self.lbl_p6_ready_lbl.setGeometry(QtCore.QRect(10, 200, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p6_ready_lbl.setFont(font)
        self.lbl_p6_ready_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p6_ready_lbl.setObjectName("lbl_p6_ready_lbl")
        self.lbl_p6_ready = QtWidgets.QLabel(self.group_player6)
        self.lbl_p6_ready.setGeometry(QtCore.QRect(110, 200, 30, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lbl_p6_ready.setFont(font)
        self.lbl_p6_ready.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p6_ready.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_p6_ready.setObjectName("lbl_p6_ready")
        self.group_player5 = QtWidgets.QGroupBox(self.LobbyMenuWidget)
        self.group_player5.setGeometry(QtCore.QRect(460, 270, 150, 231))
        self.group_player5.setObjectName("group_player5")
        self.lbl_p5_profession_lbl = QtWidgets.QLabel(self.group_player5)
        self.lbl_p5_profession_lbl.setGeometry(QtCore.QRect(10, 60, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p5_profession_lbl.setFont(font)
        self.lbl_p5_profession_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p5_profession_lbl.setObjectName("lbl_p5_profession_lbl")
        self.lbl_p5_profession_dsc = QtWidgets.QLabel(self.group_player5)
        self.lbl_p5_profession_dsc.setGeometry(QtCore.QRect(10, 120, 131, 80))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.lbl_p5_profession_dsc.setFont(font)
        self.lbl_p5_profession_dsc.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p5_profession_dsc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_p5_profession_dsc.setWordWrap(True)
        self.lbl_p5_profession_dsc.setObjectName("lbl_p5_profession_dsc")
        self.lbl_p5_name = QtWidgets.QLabel(self.group_player5)
        self.lbl_p5_name.setGeometry(QtCore.QRect(10, 40, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lbl_p5_name.setFont(font)
        self.lbl_p5_name.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p5_name.setObjectName("lbl_p5_name")
        self.lbl_p5_profession_dsc_lbl = QtWidgets.QLabel(self.group_player5)
        self.lbl_p5_profession_dsc_lbl.setGeometry(QtCore.QRect(10, 100, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p5_profession_dsc_lbl.setFont(font)
        self.lbl_p5_profession_dsc_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p5_profession_dsc_lbl.setObjectName("lbl_p5_profession_dsc_lbl")
        self.lbl_p5_name_lbl = QtWidgets.QLabel(self.group_player5)
        self.lbl_p5_name_lbl.setGeometry(QtCore.QRect(10, 20, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p5_name_lbl.setFont(font)
        self.lbl_p5_name_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p5_name_lbl.setObjectName("lbl_p5_name_lbl")
        self.lbl_p5_profession = QtWidgets.QLabel(self.group_player5)
        self.lbl_p5_profession.setGeometry(QtCore.QRect(10, 80, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lbl_p5_profession.setFont(font)
        self.lbl_p5_profession.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p5_profession.setObjectName("lbl_p5_profession")
        self.lbl_p5_ready_lbl = QtWidgets.QLabel(self.group_player5)
        self.lbl_p5_ready_lbl.setGeometry(QtCore.QRect(10, 200, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p5_ready_lbl.setFont(font)
        self.lbl_p5_ready_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p5_ready_lbl.setObjectName("lbl_p5_ready_lbl")
        self.lbl_p5_ready = QtWidgets.QLabel(self.group_player5)
        self.lbl_p5_ready.setGeometry(QtCore.QRect(110, 200, 30, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lbl_p5_ready.setFont(font)
        self.lbl_p5_ready.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p5_ready.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_p5_ready.setObjectName("lbl_p5_ready")
        self.group_player4 = QtWidgets.QGroupBox(self.LobbyMenuWidget)
        self.group_player4.setGeometry(QtCore.QRect(290, 270, 151, 231))
        self.group_player4.setObjectName("group_player4")
        self.lbl_p4_profession_lbl = QtWidgets.QLabel(self.group_player4)
        self.lbl_p4_profession_lbl.setGeometry(QtCore.QRect(10, 60, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p4_profession_lbl.setFont(font)
        self.lbl_p4_profession_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p4_profession_lbl.setObjectName("lbl_p4_profession_lbl")
        self.lbl_p4_profession_dsc = QtWidgets.QLabel(self.group_player4)
        self.lbl_p4_profession_dsc.setGeometry(QtCore.QRect(10, 120, 131, 80))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.lbl_p4_profession_dsc.setFont(font)
        self.lbl_p4_profession_dsc.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p4_profession_dsc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_p4_profession_dsc.setWordWrap(True)
        self.lbl_p4_profession_dsc.setObjectName("lbl_p4_profession_dsc")
        self.lbl_p4_name = QtWidgets.QLabel(self.group_player4)
        self.lbl_p4_name.setGeometry(QtCore.QRect(10, 40, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lbl_p4_name.setFont(font)
        self.lbl_p4_name.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p4_name.setObjectName("lbl_p4_name")
        self.lbl_p4_profession_dsc_lbl = QtWidgets.QLabel(self.group_player4)
        self.lbl_p4_profession_dsc_lbl.setGeometry(QtCore.QRect(10, 100, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p4_profession_dsc_lbl.setFont(font)
        self.lbl_p4_profession_dsc_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p4_profession_dsc_lbl.setObjectName("lbl_p4_profession_dsc_lbl")
        self.lbl_p4_name_lbl = QtWidgets.QLabel(self.group_player4)
        self.lbl_p4_name_lbl.setGeometry(QtCore.QRect(10, 20, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p4_name_lbl.setFont(font)
        self.lbl_p4_name_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p4_name_lbl.setObjectName("lbl_p4_name_lbl")
        self.lbl_p4_profession = QtWidgets.QLabel(self.group_player4)
        self.lbl_p4_profession.setGeometry(QtCore.QRect(10, 80, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lbl_p4_profession.setFont(font)
        self.lbl_p4_profession.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p4_profession.setObjectName("lbl_p4_profession")
        self.lbl_p4_ready_lbl = QtWidgets.QLabel(self.group_player4)
        self.lbl_p4_ready_lbl.setGeometry(QtCore.QRect(10, 200, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_p4_ready_lbl.setFont(font)
        self.lbl_p4_ready_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p4_ready_lbl.setObjectName("lbl_p4_ready_lbl")
        self.lbl_p4_ready = QtWidgets.QLabel(self.group_player4)
        self.lbl_p4_ready.setGeometry(QtCore.QRect(110, 200, 30, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lbl_p4_ready.setFont(font)
        self.lbl_p4_ready.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_p4_ready.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_p4_ready.setObjectName("lbl_p4_ready")
        self.frame_profession_select = QtWidgets.QFrame(self.LobbyMenuWidget)
        self.frame_profession_select.setGeometry(QtCore.QRect(10, 270, 251, 241))
        self.frame_profession_select.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_profession_select.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_profession_select.setObjectName("frame_profession_select")
        self.btn_select_rogue = QtWidgets.QPushButton(self.frame_profession_select)
        self.btn_select_rogue.setGeometry(QtCore.QRect(90, 80, 71, 71))
        self.btn_select_rogue.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_select_rogue.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_select_rogue.setFont(font)
        self.btn_select_rogue.setObjectName("btn_select_rogue")
        self.btn_select_cleric = QtWidgets.QPushButton(self.frame_profession_select)
        self.btn_select_cleric.setGeometry(QtCore.QRect(170, 80, 71, 71))
        self.btn_select_cleric.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_select_cleric.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_select_cleric.setFont(font)
        self.btn_select_cleric.setObjectName("btn_select_cleric")
        self.btn_select_wizard = QtWidgets.QPushButton(self.frame_profession_select)
        self.btn_select_wizard.setGeometry(QtCore.QRect(170, 160, 71, 71))
        self.btn_select_wizard.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_select_wizard.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_select_wizard.setFont(font)
        self.btn_select_wizard.setObjectName("btn_select_wizard")
        self.btn_select_paladin = QtWidgets.QPushButton(self.frame_profession_select)
        self.btn_select_paladin.setGeometry(QtCore.QRect(10, 160, 71, 71))
        self.btn_select_paladin.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_select_paladin.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_select_paladin.setFont(font)
        self.btn_select_paladin.setObjectName("btn_select_paladin")
        self.btn_select_monk = QtWidgets.QPushButton(self.frame_profession_select)
        self.btn_select_monk.setGeometry(QtCore.QRect(90, 160, 71, 71))
        self.btn_select_monk.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_select_monk.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_select_monk.setFont(font)
        self.btn_select_monk.setObjectName("btn_select_monk")
        self.btn_select_warrior = QtWidgets.QPushButton(self.frame_profession_select)
        self.btn_select_warrior.setGeometry(QtCore.QRect(10, 80, 71, 71))
        self.btn_select_warrior.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_select_warrior.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_select_warrior.setFont(font)
        self.btn_select_warrior.setObjectName("btn_select_warrior")
        self.lbl_set_profession = QtWidgets.QLabel(self.frame_profession_select)
        self.lbl_set_profession.setGeometry(QtCore.QRect(10, 10, 230, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_set_profession.setFont(font)
        self.lbl_set_profession.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_set_profession.setObjectName("lbl_set_profession")
        self.frame_status_buttons = QtWidgets.QFrame(self.LobbyMenuWidget)
        self.frame_status_buttons.setGeometry(QtCore.QRect(280, 530, 511, 61))
        self.frame_status_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_status_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_status_buttons.setObjectName("frame_status_buttons")
        self.btn_start = QtWidgets.QPushButton(self.frame_status_buttons)
        self.btn_start.setGeometry(QtCore.QRect(10, 10, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_start.setFont(font)
        self.btn_start.setObjectName("btn_start")
        self.btn_ready = QtWidgets.QPushButton(self.frame_status_buttons)
        self.btn_ready.setGeometry(QtCore.QRect(180, 10, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_ready.setFont(font)
        self.btn_ready.setObjectName("btn_ready")
        self.btn_exit = QtWidgets.QPushButton(self.frame_status_buttons)
        self.btn_exit.setGeometry(QtCore.QRect(350, 10, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_exit.setFont(font)
        self.btn_exit.setObjectName("btn_exit")
        self.line_3.raise_()
        self.lbl_title.raise_()
        self.lbl_connected_ip_lbl.raise_()
        self.lbl_connected_ip.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.group_player1.raise_()
        self.group_player2.raise_()
        self.group_player3.raise_()
        self.group_player6.raise_()
        self.group_player5.raise_()
        self.group_player4.raise_()
        self.frame_profession_select.raise_()
        self.frame_status_buttons.raise_()
        TPRLobbyMenu.setCentralWidget(self.LobbyMenuWidget)

        self.retranslateUi(TPRLobbyMenu)
        QtCore.QMetaObject.connectSlotsByName(TPRLobbyMenu)
        TPRLobbyMenu.setTabOrder(self.btn_start, self.btn_ready)
        TPRLobbyMenu.setTabOrder(self.btn_ready, self.btn_select_warrior)
        TPRLobbyMenu.setTabOrder(self.btn_select_warrior, self.btn_select_rogue)
        TPRLobbyMenu.setTabOrder(self.btn_select_rogue, self.btn_select_cleric)
        TPRLobbyMenu.setTabOrder(self.btn_select_cleric, self.btn_select_paladin)
        TPRLobbyMenu.setTabOrder(self.btn_select_paladin, self.btn_select_monk)
        TPRLobbyMenu.setTabOrder(self.btn_select_monk, self.btn_select_wizard)
        TPRLobbyMenu.setTabOrder(self.btn_select_wizard, self.btn_exit)

    def retranslateUi(self, TPRLobbyMenu):
        _translate = QtCore.QCoreApplication.translate
        TPRLobbyMenu.setWindowTitle(_translate("TPRLobbyMenu", "Tiny PyRPG"))
        self.lbl_title.setText(_translate("TPRLobbyMenu", "<html><head/><body><p>Tiny PyRPG</p><p>Lobby</p></body></html>"))
        self.lbl_connected_ip_lbl.setText(_translate("TPRLobbyMenu", "Connected To: "))
        self.lbl_connected_ip.setText(_translate("TPRLobbyMenu", "192.168.100.100"))
        self.group_player1.setTitle(_translate("TPRLobbyMenu", "Player 1"))
        self.lbl_p1_name_lbl.setText(_translate("TPRLobbyMenu", "Name"))
        self.lbl_p1_name.setText(_translate("TPRLobbyMenu", "Player 1 Name"))
        self.lbl_p1_profession.setText(_translate("TPRLobbyMenu", "Player 1 Profession"))
        self.lbl_p1_profession_lbl.setText(_translate("TPRLobbyMenu", "Profession"))
        self.lbl_p1_profession_dsc_lbl.setText(_translate("TPRLobbyMenu", "Description"))
        self.lbl_p1_profession_dsc.setText(_translate("TPRLobbyMenu", "Player 1 Profession Description"))
        self.lbl_p1_ready_lbl.setText(_translate("TPRLobbyMenu", "Ready:"))
        self.lbl_p1_ready.setText(_translate("TPRLobbyMenu", "No"))
        self.group_player2.setTitle(_translate("TPRLobbyMenu", "Player 2"))
        self.lbl_p2_profession_lbl.setText(_translate("TPRLobbyMenu", "Profession"))
        self.lbl_p2_profession_dsc.setText(_translate("TPRLobbyMenu", "Player 1 Profession Description"))
        self.lbl_p2_name.setText(_translate("TPRLobbyMenu", "Player 1 Name"))
        self.lbl_p2_profession_dsc_lbl.setText(_translate("TPRLobbyMenu", "Description"))
        self.lbl_p2_name_lbl.setText(_translate("TPRLobbyMenu", "Name"))
        self.lbl_p2_profession.setText(_translate("TPRLobbyMenu", "Player 1 Profession"))
        self.lbl_p2_ready_lbl.setText(_translate("TPRLobbyMenu", "Ready:"))
        self.lbl_p2_ready.setText(_translate("TPRLobbyMenu", "No"))
        self.group_player3.setTitle(_translate("TPRLobbyMenu", "Player 3"))
        self.lbl_p3_profession_lbl.setText(_translate("TPRLobbyMenu", "Profession"))
        self.lbl_p3_profession_dsc.setText(_translate("TPRLobbyMenu", "Player 1 Profession Description"))
        self.lbl_p3_name.setText(_translate("TPRLobbyMenu", "Player 1 Name"))
        self.lbl_p3_profession_dsc_lbl.setText(_translate("TPRLobbyMenu", "Description"))
        self.lbl_p3_name_lbl.setText(_translate("TPRLobbyMenu", "Name"))
        self.lbl_p3_profession.setText(_translate("TPRLobbyMenu", "Player 1 Profession"))
        self.lbl_p3_ready_lbl.setText(_translate("TPRLobbyMenu", "Ready:"))
        self.lbl_p3_ready.setText(_translate("TPRLobbyMenu", "No"))
        self.group_player6.setTitle(_translate("TPRLobbyMenu", "Player 6"))
        self.lbl_p6_profession_lbl.setText(_translate("TPRLobbyMenu", "Profession"))
        self.lbl_p6_profession_dsc.setText(_translate("TPRLobbyMenu", "Player 1 Profession Description"))
        self.lbl_p6_name.setText(_translate("TPRLobbyMenu", "Player 1 Name"))
        self.lbl_p6_profession_dsc_lbl.setText(_translate("TPRLobbyMenu", "Description"))
        self.lbl_p6_name_lbl.setText(_translate("TPRLobbyMenu", "Name"))
        self.lbl_p6_profession.setText(_translate("TPRLobbyMenu", "Player 1 Profession"))
        self.lbl_p6_ready_lbl.setText(_translate("TPRLobbyMenu", "Ready:"))
        self.lbl_p6_ready.setText(_translate("TPRLobbyMenu", "No"))
        self.group_player5.setTitle(_translate("TPRLobbyMenu", "Player 5"))
        self.lbl_p5_profession_lbl.setText(_translate("TPRLobbyMenu", "Profession"))
        self.lbl_p5_profession_dsc.setText(_translate("TPRLobbyMenu", "Player 1 Profession Description"))
        self.lbl_p5_name.setText(_translate("TPRLobbyMenu", "Player 1 Name"))
        self.lbl_p5_profession_dsc_lbl.setText(_translate("TPRLobbyMenu", "Description"))
        self.lbl_p5_name_lbl.setText(_translate("TPRLobbyMenu", "Name"))
        self.lbl_p5_profession.setText(_translate("TPRLobbyMenu", "Player 1 Profession"))
        self.lbl_p5_ready_lbl.setText(_translate("TPRLobbyMenu", "Ready:"))
        self.lbl_p5_ready.setText(_translate("TPRLobbyMenu", "No"))
        self.group_player4.setTitle(_translate("TPRLobbyMenu", "Player 4"))
        self.lbl_p4_profession_lbl.setText(_translate("TPRLobbyMenu", "Profession"))
        self.lbl_p4_profession_dsc.setText(_translate("TPRLobbyMenu", "Player 1 Profession Description"))
        self.lbl_p4_name.setText(_translate("TPRLobbyMenu", "Player 1 Name"))
        self.lbl_p4_profession_dsc_lbl.setText(_translate("TPRLobbyMenu", "Description"))
        self.lbl_p4_name_lbl.setText(_translate("TPRLobbyMenu", "Name"))
        self.lbl_p4_profession.setText(_translate("TPRLobbyMenu", "Player 1 Profession"))
        self.lbl_p4_ready_lbl.setText(_translate("TPRLobbyMenu", "Ready:"))
        self.lbl_p4_ready.setText(_translate("TPRLobbyMenu", "No"))
        self.btn_select_rogue.setText(_translate("TPRLobbyMenu", "Rogue"))
        self.btn_select_cleric.setText(_translate("TPRLobbyMenu", "Cleric"))
        self.btn_select_wizard.setText(_translate("TPRLobbyMenu", "Wizard"))
        self.btn_select_paladin.setText(_translate("TPRLobbyMenu", "Paladin"))
        self.btn_select_monk.setText(_translate("TPRLobbyMenu", "Monk"))
        self.btn_select_warrior.setText(_translate("TPRLobbyMenu", "Warrior"))
        self.lbl_set_profession.setText(_translate("TPRLobbyMenu", "Change Profession"))
        self.btn_start.setText(_translate("TPRLobbyMenu", "Start"))
        self.btn_ready.setText(_translate("TPRLobbyMenu", "Ready"))
        self.btn_exit.setText(_translate("TPRLobbyMenu", "Exit"))
